### ISSUE TITLE
Smart Contract Agreement  between Artist and Platform

### ISSUE THREAD

**Issue by joeephwild** [Looop-content-Dapp/Looop__contract2#2]
Document and discuss the implementation of a Smart Contract agreement between an Artist and the Platform.

### Tasks

- [ ] Define contract requirements
- [ ] Write the smart contract
- [ ] Conduct initial testing
- [ ] Audit the contract
- [ ] Deploy to Testnet/Mainnet
